[package]
name = "nebula-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Nebula: command line client (local mode and remote mode)"

[dependencies]
nebula-core = { path = "../nebula-core" }
nebula-engine = { path = "../nebula-engine" }
nebula-cluster = { path = "../nebula-cluster" }
nebula-sql = { path = "../nebula-sql" }
nebula-config = { path = "../nebula-config" }
nebula-server = { path = "../nebula-server" }
rpassword = "7"

# Windows 资源(图标/版本信息)编译;仅 Windows 目标需要。
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[[bin]]
name = "nebula"
path = "src/main.rs"
